import type{SupabaseClient,User}from"@supabase/supabase-js";import{firstApply}from"./first-apply";
export const fastApplyExternalId=(userId:string,profileId:string)=>`${userId}:${profileId}`;const compact=(value:Record<string,any>)=>Object.fromEntries(Object.entries(value).filter(([,item])=>item!==undefined&&item!==null&&item!==""));
export function fastApplyProfilePayload(user:User,profile:any,resume:any){
 const data=resume?.extracted_data?.data||resume?.extracted_data||{},contact=data.contact||{},saved=profile?.applicant_profile||{},nameParts=String(data.name||contact.name||"").trim().split(/\s+/).filter(Boolean);
 const present=(item:any)=>item!==undefined&&item!==null&&item!==""&&(!Array.isArray(item)||item.length>0);
 const value=(key:string,...fallbacks:any[])=>present(saved[key])?saved[key]:fallbacks.find(present);
 const firstName=value("firstName",data.firstName,contact.firstName,nameParts[0]),lastName=value("lastName",data.lastName,contact.lastName,nameParts.slice(1).join(" "));
 return compact({
  name:[firstName,value("middleName",data.middleName),lastName].filter(Boolean).join(" ")||data.name||contact.name,
  firstName,middleName:value("middleName",data.middleName),lastName,email:value("email",data.email,contact.email,user.email),
  phoneCountryCode:value("phoneCountryCode",data.phoneCountryCode,contact.phoneCountryCode),phoneNumber:value("phoneNumber",data.phoneNumber,contact.phone),streetAddress:value("streetAddress",data.streetAddress,contact.streetAddress),currentCity:value("currentCity",data.currentCity,contact.city),state:value("state",data.state,contact.state),zipcode:value("zipcode",data.zipcode,contact.zipcode),country:value("country",data.country,contact.country),timezone:value("timezone",data.timezone),
  headline:value("headline",data.headline,profile.target_roles?.[0]),summary:value("summary",data.summary),yearsOfExperience:value("yearsOfExperience",data.yearsOfExperience),
  desiredSalary:value("desiredSalary",profile.salary_min?String(profile.salary_min):undefined,data.desiredSalary),desiredSalaryCurrency:value("desiredSalaryCurrency",profile.salary_currency,data.desiredSalaryCurrency),desiredSalaryNegotiable:value("desiredSalaryNegotiable",data.desiredSalaryNegotiable),currentSalary:value("currentSalary",data.currentSalary),currentSalaryCurrency:value("currentSalaryCurrency",data.currentSalaryCurrency),noticePeriod:value("noticePeriod",data.noticePeriod),remotePreference:value("remotePreference",profile.work_mode,data.remotePreference),willingToRelocate:value("willingToRelocate",data.willingToRelocate),
  coverLetter:value("coverLetter",data.coverLetter),linkedinURL:value("linkedinURL",data.linkedinURL,contact.linkedin),githubURL:value("githubURL",data.githubURL,contact.github),website:value("website",data.website,data.portfolioURL,contact.website),twitterURL:value("twitterURL",data.twitterURL,contact.twitter),additionalLinks:value("additionalLinks",data.additionalLinks),
  skills:value("skills",data.skills,[]),experience:value("experience",data.experience,data.roles,[]),education:value("education",data.education,[]),projects:value("projects",data.projects,[]),references:value("references",data.references,[]),certifications:value("certifications",data.certifications,[]),languages:value("languages",data.languages,[]),
  gender:value("gender",data.gender),dateOfBirth:value("dateOfBirth",data.dateOfBirth),workAuthorization:value("workAuthorization",data.workAuthorization),requiresSponsorship:value("requiresSponsorship",data.requiresSponsorship),disabilityStatus:value("disabilityStatus",data.disabilityStatus),veteranStatus:value("veteranStatus",data.veteranStatus),race:value("race",data.race),ethnicity:value("ethnicity",data.ethnicity),securityClearance:value("securityClearance",data.securityClearance),howDidYouHearAboutUs:value("howDidYouHearAboutUs",data.howDidYouHearAboutUs)
 });
}
export async function primaryResumeForProfile(supabase:SupabaseClient,userId:string,profileId:string){const link=await supabase.from("job_profile_resumes").select("resume_id").eq("user_id",userId).eq("job_profile_id",profileId).order("is_primary",{ascending:false}).order("created_at",{ascending:false}).limit(1).maybeSingle();if(link.error)throw link.error;if(!link.data?.resume_id)throw new Error("Add a resume to this job profile before using Scout AI.");const result=await supabase.from("resumes").select("id,name,storage_path,extracted_data").eq("id",link.data.resume_id).eq("user_id",userId).single();if(result.error||!result.data)throw new Error("Scout could not find this profile's resume.");return result.data;}
export async function ensureFastApplyApplicant(supabase:SupabaseClient,user:User,profile:any){const externalId=fastApplyExternalId(user.id,profile.id),resume=await primaryResumeForProfile(supabase,user.id,profile.id),sync=await supabase.from("fastapply_applicant_sync").select("*").eq("user_id",user.id).eq("job_profile_id",profile.id).maybeSingle();if(sync.error)throw sync.error;try{await firstApply.upsertApplicantProfile(externalId,fastApplyProfilePayload(user,profile,resume));let remoteResumeId=sync.data?.remote_resume_id||null;/* A local sync row is not evidence the remote still holds the resume. If the applicant vanished upstream — deleted, or the api key now points at a different account — the upsert above recreates the profile, but an unchanged resume id would skip the upload and leave remote_resume_id pointing at nothing. */let remoteHasResume=false;if(remoteResumeId&&sync.data?.resume_id===resume.id){try{const remote:any[]=await firstApply.listApplicantResumes(externalId)||[];remoteHasResume=remote.some((item:any)=>String(item?.id||item?.resumeId||"")===String(remoteResumeId))}catch{remoteHasResume=false}}if(sync.data?.resume_id!==resume.id||!remoteHasResume){const downloaded=await supabase.storage.from("resumes").download(resume.storage_path);if(downloaded.error||!downloaded.data)throw new Error("Scout could not read this profile's resume.");const uploaded:any=await firstApply.uploadApplicantResume(externalId,downloaded.data,resume.name||"resume.pdf",`Scout resume ${resume.id}`);remoteResumeId=uploaded?.id||uploaded?.resumeId||null}const now=new Date().toISOString(),saved=await supabase.from("fastapply_applicant_sync").upsert({user_id:user.id,job_profile_id:profile.id,external_id:externalId,resume_id:resume.id,remote_resume_id:remoteResumeId,profile_synced_at:now,resume_synced_at:sync.data?.resume_id===resume.id?sync.data?.resume_synced_at:now,last_error:null,updated_at:now},{onConflict:"user_id,job_profile_id"});if(saved.error)throw saved.error;return{externalId,resume,remoteResumeId}}catch(error){await supabase.from("fastapply_applicant_sync").upsert({user_id:user.id,job_profile_id:profile.id,external_id:externalId,resume_id:resume.id,last_error:error instanceof Error?error.message:String(error),updated_at:new Date().toISOString()},{onConflict:"user_id,job_profile_id"});throw error}}
