type RequestOptions = { method?: string; body?: unknown; query?: Record<string, string | number | boolean | undefined | string[]>; authenticated?: boolean; bearer?: boolean };
export class FirstApplyError extends Error { status:number; constructor(message:string,status=502){super(message);this.name="FirstApplyError";this.status=status;} }
function configuration(){const baseUrl=import.meta.env.FIRSTAPPLY_API_URL?.trim().replace(/\/$/,""),apiKey=import.meta.env.FIRSTAPPLY_API_TOKEN?.trim();if(!baseUrl||!apiKey)throw new FirstApplyError("Scout AI is not connected to the application service yet.",503);if(!apiKey.startsWith("fa_"))throw new FirstApplyError("Scout AI requires a FastApply project API key.",503);return{baseUrl,apiKey}}
export async function firstApplyRequest<T=any>(path:string,options:RequestOptions={}):Promise<T>{const{baseUrl,apiKey}=configuration(),url=new URL(`${baseUrl}${path.startsWith("/")?path:`/${path}`}`);for(const[k,value]of Object.entries(options.query||{})){if(value===undefined)continue;if(Array.isArray(value))value.forEach(item=>url.searchParams.append(k,item));else url.searchParams.set(k,String(value))}
const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),25000);try{const response=await fetch(url,{method:options.method||(options.body===undefined?"GET":"POST"),headers:{accept:"application/json",...(options.authenticated===false?{}:options.bearer?{authorization:`Bearer ${apiKey}`}:{"x-api-key":apiKey}),...(options.body===undefined?{}:{"content-type":"application/json"})},body:options.body===undefined?undefined:JSON.stringify(options.body),signal:controller.signal});const text=await response.text();let payload:any=null;try{payload=text?JSON.parse(text):null}catch{payload=text}if(!response.ok||payload?.success===false)throw new FirstApplyError(String(payload?.message||payload?.error||`Application service returned ${response.status}`),response.status||502);return(payload?.data??payload)as T}catch(error){if(error instanceof FirstApplyError)throw error;if(error instanceof DOMException&&error.name==="AbortError")throw new FirstApplyError("The application service took too long to respond.",504);throw new FirstApplyError("Scout could not reach the application service.",502)}finally{clearTimeout(timeout)}}
function uniqueJobs(results:any[]){const seen=new Set<string>();return results.filter(job=>{const key=String(job.jobUrl||job.url||job.applyUrl||job.id||"");if(!key||seen.has(key))return false;seen.add(key);return true})}
export const firstApply={
 searchJobs:async(body:Record<string,any>)=>{const request={keywords:body.keywords||[],platforms:body.platforms||["greenhouse","lever","ashby","workable","recruitee","rippling"],locations:body.locations||[],workModes:body.workModes||[],jobTypes:body.jobTypes||[],experienceLevels:body.experienceLevels||[],datePosted:body.datePosted||"24h",companyBlacklist:body.companyBlacklist||[],profileId:body.profileId,profileData:body.profileData};let current=await firstApplyRequest<any>("/api/v1/job-matcher/start",{method:"POST",body:request,bearer:true}),jobs:any[]=[];for(let count=0;count<50;count++){if(current?.url||current?.applyUrl)jobs.push(current);if(current?.done||current?.scanning||!current?.sessionId)break;if(jobs.length>=Number(current.matchLimit||50))break;current=await firstApplyRequest<any>("/api/v1/job-matcher/next",{method:"POST",body:{sessionId:current.sessionId},bearer:true})}jobs=uniqueJobs(jobs);return{jobs,total:jobs.length,sessionId:current?.sessionId,done:Boolean(current?.done),scanning:Boolean(current?.scanning),nextScanAt:current?.nextScanAt}},
 canApply:(jobId:string,externalUserId:string,jobUrl?:string)=>firstApplyRequest<any>("/api/v1/b2b/can-apply",{query:{jobId,externalUserId,jobUrl}}),
 createAutomation:(body:Record<string,unknown>)=>firstApplyRequest<any>("/api/v1/b2b/automations",{method:"POST",body}),
 cancelAutomation:(id:string)=>firstApplyRequest<any>(`/api/v1/b2b/automations/${id}`,{method:"DELETE"}),
 getAutomation:(id:string)=>firstApplyRequest<any>(`/api/v1/b2b/automations/${id}`),
};
