import { serverEnv } from "./server-env";
type QueryValue = string | number | boolean | undefined | string[];
type RequestOptions = { method?: string; body?: unknown; query?: Record<string, QueryValue>; timeoutMs?: number };
export class FirstApplyError extends Error { status:number; details:unknown; constructor(message:string,status=502,details?:unknown){super(message);this.name="FirstApplyError";this.status=status;this.details=details;} }
// serverEnv, not import.meta.env: a literal env access is inlined into the build
// output, so a rotated key kept failing until the next deploy rebuilt the bundle.
function configuration(){const configured=serverEnv("FIRSTAPPLY_API_URL")?.replace(/\/+$/,"");const baseUrl=configured||"https://api.fastapply.co",apiKey=serverEnv("FIRSTAPPLY_API_TOKEN");if(!apiKey)throw new FirstApplyError("Scout AI is not connected to the application service yet.",503);if(!apiKey.startsWith("fa_"))throw new FirstApplyError("Scout AI requires a valid application-service key.",503);return{root:baseUrl.endsWith("/api/v1")?baseUrl:`${baseUrl}/api/v1`,apiKey};}
function errorMessage(payload:any,fallback:string){if(Array.isArray(payload?.message))return payload.message.join(" ");return String(payload?.message||payload?.error||fallback);}
export async function firstApplyRequest<T=any>(path:string,options:RequestOptions={}):Promise<T>{const{root,apiKey}=configuration(),url=new URL(`${root}${path.startsWith("/")?path:`/${path}`}`);for(const[key,value]of Object.entries(options.query||{})){if(value===undefined)continue;if(Array.isArray(value))value.forEach(item=>url.searchParams.append(key,item));else url.searchParams.set(key,String(value));}const multipart=options.body instanceof FormData,requestBody:any=options.body===undefined?undefined:multipart?options.body:JSON.stringify(options.body),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),options.timeoutMs||60000);try{const response=await fetch(url,{method:options.method||(options.body===undefined?"GET":"POST"),headers:{accept:"application/json","x-api-key":apiKey,...(options.body===undefined||multipart?{}:{"content-type":"application/json"})},body:requestBody,signal:controller.signal});if(response.status===204)return undefined as T;const text=await response.text();let payload:any=null;try{payload=text?JSON.parse(text):null}catch{payload=text}if(!response.ok||payload?.success===false)throw new FirstApplyError(errorMessage(payload,`The application service returned ${response.status}.`),response.status||502,payload);return(payload?.success===true&&payload?.data!==undefined?payload.data:payload)as T}catch(error){if(error instanceof FirstApplyError)throw error;if(error instanceof DOMException&&error.name==="AbortError")throw new FirstApplyError("The application service took too long to respond.",504);throw new FirstApplyError("Scout could not reach the application service.",502,error)}finally{clearTimeout(timeout)}}
const applicantPath=(externalId:string)=>`/applicants/${encodeURIComponent(externalId)}`;
export const firstApply={
 upsertApplicant:(externalId:string,body:Record<string,unknown>)=>firstApplyRequest(applicantPath(externalId),{method:"PUT",body}),getApplicant:(externalId:string)=>firstApplyRequest(applicantPath(externalId)),deleteApplicant:(externalId:string)=>firstApplyRequest(applicantPath(externalId),{method:"DELETE"}),
 upsertApplicantProfile:(externalId:string,body:Record<string,unknown>)=>firstApplyRequest(`${applicantPath(externalId)}/profile`,{method:"PUT",body}),getApplicantProfile:(externalId:string)=>firstApplyRequest(`${applicantPath(externalId)}/profile`),listApplicantResumes:(externalId:string)=>firstApplyRequest<any[]>(`${applicantPath(externalId)}/resumes`),
 uploadApplicantResume:(externalId:string,file:Blob,fileName:string,description?:string)=>{const form=new FormData();form.append("file",file,fileName);if(description)form.append("description",description);return firstApplyRequest(`${applicantPath(externalId)}/resume`,{method:"POST",body:form,timeoutMs:120000})},deleteApplicantResume:(externalId:string,resumeId:string)=>firstApplyRequest(`${applicantPath(externalId)}/resumes/${encodeURIComponent(resumeId)}`,{method:"DELETE"}),
 searchJobs:(body:Record<string,unknown>)=>firstApplyRequest<any>("/jobs/search",{method:"POST",body,timeoutMs:120000}),
 matchApplicant:(externalId:string,body:Record<string,unknown>)=>firstApplyRequest<any[]>(`${applicantPath(externalId)}/match`,{method:"POST",body,timeoutMs:120000}),applyApplicant:(externalId:string,jobUrl:string)=>firstApplyRequest<{automationId:string;queued:boolean}>(`${applicantPath(externalId)}/apply`,{method:"POST",body:{jobUrl},timeoutMs:120000}),getApplicantApplications:(externalId:string,page=1,limit=20)=>firstApplyRequest<any>(`${applicantPath(externalId)}/applications`,{query:{page,limit}}),
 canApply:(externalUserId:string,jobUrl:string,jobId?:string)=>firstApplyRequest<any>("/b2b/can-apply",{query:{externalUserId,jobUrl,jobId}}),createAutomation:(body:Record<string,unknown>)=>firstApplyRequest<any>("/b2b/automations",{method:"POST",body,timeoutMs:120000}),listAutomations:(query:Record<string,QueryValue>={})=>firstApplyRequest<any>("/b2b/automations",{query}),getAutomation:(id:string)=>firstApplyRequest<any>(`/b2b/automations/${encodeURIComponent(id)}`),cancelAutomation:(id:string)=>firstApplyRequest<void>(`/b2b/automations/${encodeURIComponent(id)}`,{method:"DELETE"}),retryAutomation:(id:string)=>firstApplyRequest<any>(`/b2b/automations/${encodeURIComponent(id)}/retry`,{method:"POST",body:{}}),getUsage:()=>firstApplyRequest<any>("/b2b/usage"),getUsageHistory:(months=6)=>firstApplyRequest<any>("/b2b/usage/history",{query:{months}})};
