import type{APIRoute}from"astro";import{assertSameOrigin,errorMessage,json,list,requireUser}from"../../../lib/api";import{firstApply,FirstApplyError}from"../../../lib/first-apply";import{ensureFastApplyApplicant,findPrimaryResume}from"../../../lib/fastapply-applicant";import{assertAgentProfileComplete,checkJobProfileGate}from"../../../lib/agent-profile-gate";import{getDemoState}from"../../../lib/demo-store";import{getPostHogServer}from"../../../lib/posthog-server";import{rateLimit,tooManyRequests}from"../../../lib/rate-limit";import{assertCanActivateAgent}from"../../../lib/entitlements";export const prerender=false;export const maxDuration=120;
const jobType=(v:string)=>v==="full_time"?"full-time":v==="part_time"?"part-time":v;const posted=(v:string)=>({past_day:"24h",past_week:"7d",past_month:"30d"}[v]||v||"7d");function fields(b:any){const roles=list(b.roles).slice(0,20),locations=list(b.locations).slice(0,20);if(!roles.length)throw new Error("Tell Scout at least one role to target.");if(!locations.length)throw new Error("Tell Scout at least one location to search.");return{roles,locations,company_blacklist:list(b.companyBlacklist).slice(0,50),employment_types:list(b.employmentTypes),experience_levels:list(b.experienceLevels),work_modes:list(b.workModes),platforms:list(b.platforms).length?list(b.platforms):["greenhouse","lever","ashby","workable","recruitee","workday","smartrecruiters"],date_posted:posted(String(b.datePosted||"7d")),max_applications_per_day:Math.max(1,Math.min(100,Number(b.maxApplicationsPerDay||10))),schedule_type:String(b.scheduleType||"daily"),schedule_time:String(b.scheduleTime||"09:00"),schedule_days:list(b.scheduleDays).map(Number).filter(Number.isInteger),accuracy_threshold:Math.max(50,Math.min(100,Number(b.accuracyThreshold||70))),stealth_apply:b.stealthApply===true,resume_per_job:b.resumePerJob===true}}function requireAi(c:any){const u=requireUser(c);if(c.locals.scoutProfile?.assistant_type!=="ai")throw new Response(JSON.stringify({error:"Scout AI settings are only available for AI Agent accounts."}),{status:403,headers:{"content-type":"application/json"}});return u}function automationBody(u:any,p:any,x:any){return{externalUserId:`${u.id}:${p.id}`,name:`Scout AI — ${p.name}`,applicationMode:"platform_search",searchKeywords:x.roles,platforms:x.platforms,cities:x.locations,workModes:x.work_modes,jobTypes:(x.employment_types||[]).map(jobType),experienceLevels:x.experience_levels,maxApplicationsPerDay:x.max_applications_per_day,scheduleType:x.schedule_type,scheduleTime:x.schedule_time,scheduleDays:x.schedule_days,applyMatchingJobsOnly:true,useTailoredResume:Boolean(x.resume_per_job),companyBlacklist:x.company_blacklist,externalUserEmail:u.email,externalMetadata:{scoutProfileId:p.id,accuracyThreshold:x.accuracy_threshold,stealthApply:x.stealth_apply}}}
export const GET:APIRoute=async c=>{try{const u=requireAi(c);if(c.locals.demoMode)return json({configs:(getDemoState(u.id,u.email)as any).aiAgentConfigs||[],usage:null});const r=await c.locals.supabase!.from("ai_agent_configs").select("*").order("created_at");if(r.error)throw r.error;return json({configs:r.data||[],usage:await firstApply.getUsage().catch(()=>null)})}catch(e){if(e instanceof Response)return e;return json({error:errorMessage(e)},{status:e instanceof FirstApplyError?e.status:400})}};
export const POST:APIRoute=async c=>{try{assertSameOrigin(c);const u=requireAi(c),b=await c.request.json(),profileId=String(b.jobProfileId||""),action=String(b.action||"save");if(!profileId)return json({error:"Choose a job profile."},{status:400});const values=fields(b);
// Paywall: activating the agent starts billable automated applications.
// Saving a draft and pausing stay free so an unpaid member can still prepare.
if(action!=="save"&&action!=="pause")assertCanActivateAgent(c.locals.entitlement);
if(c.locals.demoMode){const state:any=getDemoState(u.id,u.email);state.aiAgentConfigs||=[];let old=state.aiAgentConfigs.find((x:any)=>x.job_profile_id===profileId),next={...(old||{}),id:old?.id||crypto.randomUUID(),job_profile_id:profileId,...values,status:action==="pause"?"paused":action==="save"?(old?.status||"draft"):"active"};old?Object.assign(old,next):state.aiAgentConfigs.push(next);return json({ok:true,config:next})}const db=c.locals.supabase!;if(!(await rateLimit(db,`ai-agent:${u.id}`,{max:20,windowSeconds:60})).allowed)return tooManyRequests();const pr=await db.from("job_profiles").select("*").eq("id",profileId).eq("user_id",u.id).single();if(pr.error)return json({error:"Job profile not found."},{status:404});
// Profile-completeness gate. FastApply silently refuses to run an automation whose applicant
// profile is missing required answers, so an incomplete profile would leave Scout reporting
// "running" while nothing is ever submitted. Checked before the config row is flipped to
// "activating" so a rejected activation cannot strand the row mid-state.
if(action!=="save"&&action!=="pause"){const gate=checkJobProfileGate(u,pr.data,await findPrimaryResume(db,u.id,profileId));if(!gate.isComplete){const phBlocked=getPostHogServer();if(phBlocked){phBlocked.capture({distinctId:u.id,event:"ai_agent_activation_blocked",properties:{job_profile_id:profileId,missing_sections:gate.incompleteSections.map(s=>s.id)}});await phBlocked.flush()}assertAgentProfileComplete(gate,profileId)}}
const ex=await db.from("ai_agent_configs").select("*").eq("job_profile_id",profileId).eq("user_id",u.id).maybeSingle();if(ex.error)throw ex.error;const saved=await db.from("ai_agent_configs").upsert({user_id:u.id,job_profile_id:profileId,...values,status:action==="save"?(ex.data?.status||"draft"):action==="pause"?"paused":"activating",updated_at:new Date().toISOString()},{onConflict:"user_id,job_profile_id"}).select("*").single();if(saved.error)throw saved.error;if(action==="save")return json({ok:true,config:saved.data});if(action==="pause"){if(saved.data.first_apply_id)await firstApply.cancelAutomation(saved.data.first_apply_id);const updated=await db.from("ai_agent_configs").update({status:"paused",last_error:null,synced_at:new Date().toISOString()}).eq("id",saved.data.id).select("*").single();if(updated.error)throw updated.error;const phPause=getPostHogServer();if(phPause){phPause.capture({distinctId:u.id,event:"ai_agent_paused",properties:{job_profile_id:profileId}});await phPause.flush()}return json({ok:true,config:updated.data})}await ensureFastApplyApplicant(db,u,pr.data);if(saved.data.first_apply_id){try{await firstApply.cancelAutomation(saved.data.first_apply_id)}catch{}}const remote=await firstApply.createAutomation(automationBody(u,pr.data,saved.data)),id=String(remote?.id||"");if(!id)throw new Error("The application service did not return an automation ID.");const updated=await db.from("ai_agent_configs").update({first_apply_id:id,status:"active",remote_payload:remote,last_error:null,synced_at:new Date().toISOString()}).eq("id",saved.data.id).select("*").single();if(updated.error)throw updated.error;const phActivate=getPostHogServer();if(phActivate){phActivate.capture({distinctId:u.id,event:"ai_agent_activated",properties:{job_profile_id:profileId,max_applications_per_day:values.max_applications_per_day,schedule_type:values.schedule_type}});await phActivate.flush()}return json({ok:true,config:updated.data})}catch(e){if(e instanceof Response)return e;return json({error:errorMessage(e)},{status:e instanceof FirstApplyError?e.status:400})}};
